# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Jungwoo LEE
baseurl: ""
url: "https://www.jungwoo3490.github.io"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Jungwoo Lee
  url: https://jungwoo3490.github.io/
  email: jungwoo3490@naver.com
  github: jungwoo3490
  twitter:

# Custom vars
version: 3.4.1
github:
  repo: https://github.com/jungwoo3490/jungwoo3490.github.io
